FinalProject/FinalProject/config/routes.rb
FinalProject::Application.routes.draw do
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  root :to => 'homes#landing'
  match 'dashboard', to: "homes#index"
  resources :items do
    get :approve
    collection do
      get 'user_and_approved_items_index'
    end
  end

end

FinalProject/FinalProject/app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  attr_accessible :category, :chance_of_rain, :high, :low, :verified,
                  :image, :title, :gender
  validates :image, :presence => true
  validates :title, :presence => true
end

FinalProject/FinalProject/app/models/user.rb
class User < ActiveRecord::Base
  has_many :items
  attr_accessible :provider, :uid
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.sex = auth.extra.raw_info.gender
      user.user_image_url = auth.info.image
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

FinalProject/FinalProject/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

FinalProject/FinalProject/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    unless current_user
      return redirect_to :root
    end
  end

  def landing
    if current_user
      return redirect_to dashboard_path
    end
  end
end

FinalProject/FinalProject/app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_filter :logged_in?, only: [:new, :create]
  before_filter :admin?, only: [:approve, :destroy, :index]

  def admin?
    if not (current_user and current_user.admin?)
      flash[:notice] = "WHY you no admin!!"
      redirect_to :root
    end
  end

  def logged_in?
    unless current_user
      flash[:notice] = "Please, log in"
      redirect_to :root
    end
  end
  
  def index
    @items = Item.where(:verified => false)
  end

  def new
    @item = Item.new
  end

  def destroy
    @item = Item.find(params[:id])
    @item.delete
    render :nothing => true
  end

  def approve
    @item = Item.find(params[:item_id])
    @item.verified = true
    @item.save
    render :json => true
  end

  def create
    @item = current_user.items.new(params[:item])
    if @item.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def user_and_approved_items_index
    passed_low = params[:low].to_i
    passed_high = params[:high].to_i
    passed_rain = params[:rain].to_i
    @items = current_user.items.where("? >= high OR ? >= low",passed_high,passed_low) | Item.where(:verified => true).where("? >= high OR ? >= low",passed_high,passed_low)
    Rails.logger.debug @items.to_json
    render :json => @items.group_by{|x| x.category}
  end
end

FinalProject/FinalProject/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to dashboard_url
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

FinalProject/FinalProject/app/helpers/application_helper.rb
module ApplicationHelper
end

FinalProject/FinalProject/app/helpers/homes_helper.rb
module HomesHelper
end

FinalProject/FinalProject/app/helpers/sessions_helper.rb
module SessionsHelper
end

FinalProject/FinalProject/app/views/homes/_zip.html.erb
<h3>No location huh?</br>
  Well enter you F***ing zip then</h3>
<form class="zip-form form-horizontal">
  <div class="control-group">
    <div class="controls">
      <input type="text" name="zip" class="input-large" placeholder="Enter zip code..."autofocus>
      <button type="submit" id="invis" class="btn">Search</button>
    </div>
  </div>
</form>

FinalProject/FinalProject/app/views/homes/index.html.erb
<p class="lead">Weather information as of: <%= Time.now.strftime("%A %B %-d %Y, %r") %></p>
<div id="header"></div>
<div id="items"></div>

<%= link_to new_item_path, :class=>"btn btn-primary btn-large", :id => "add_item_button" do %>
  <i class="icon-plus icon-2x"></i>
  Add Item
<% end %>
<%= javascript_include_tag "render_templates" %>

FinalProject/FinalProject/app/views/homes/landing.html.erb
<div class="jumbotron">
        <h1>WTFShouldIWear?</h1>
        <p class="lead">Flats or Boots? With WTFShouldIWear this is no longer a problem! We use advanced weather data and hip items to keep you looking fresh anytime anywhere!</p>
        <%= link_to " <i class=\"icon-facebook-sign icon-2x\"></i>   Sign in with Facebook".html_safe, "/auth/facebook", id: "sign_in", :class => "btn btn-primary btn-large" %>
 </div>

FinalProject/FinalProject/app/views/items/index.html.erb
<% attrs = [:title, :high, :low, :chance_of_rain] %>

<div class="row">
  <% ([:image] + attrs).each do |attr| %>
    <div class="span2">
      <%= attr.to_s.titleize %>
    </div>
  <% end %>
</div>

<div id="admin_items">
<% @items.each do |item| %>
  <div class="row">
    <div class="span2">
      <%= image_tag item.image %>
    </div>
    <% attrs.each do |attr| %>
      <div class="span2">
        <%= item[attr] %>
      </div>
    <% end %>
    <div class="span2">
      <%= link_to 'Delete', item, :class => 'btn btn-danger', :method => :delete, :confirm => "Are you sure?", :remote => true %>
      <%= link_to 'Approve', item_approve_path(item), :class => 'btn btn-success', :remote => true %>
    </div>
  </div>
<% end %>
</div>

FinalProject/FinalProject/app/views/items/new.html.erb
<div class="row">
  <div class="span3">

    <%= form_for(@item) do |f| %>
      <h4>High and Low</h4>
      <div class="temp-slider"></div>
      <div class="temp-value"></div>
      <div class="field">
        <%= f.hidden_field(:high) %>
      </div>

    <div class="field">
      <%= f.hidden_field(:low) %>
    </div>

    <div class="field">
      <h4>Chance of Rain</h4>
      <div class="precip-slider"></div>
      <div class="precip-value"></div></br>
      <%= f.hidden_field(:chance_of_rain) %>
    </div>

    <div class="field">
      <%= f.label :image %> 
      <%= f.hidden_field :image, :id => "image"%> 
      <div id="displayedimage">
        <font color="red"> No image selected.
        </font>
      </div>
    </div>

    <div class="field">
      <%= f.label :category %>
      <%= f.select :category, [["Headwear", 0], ["Upper body", 1], ["Lower body", 2], ["Accessory", 3]] %>
    </div>

    <div class="field">
      <%= f.label :gender %> 
      <%= f.select :gender, [["Male", "male"], ["Female", "female"], ["Unisex", "unisex"]] %>
    </div>

    <div class="field">
      <%= f.label :title %> 
      <%= f.text_field :title %> 
    </div>

    <div class="actions">
      <%= f.submit "Save" %> 
    </div>

  <% end %>
  </div>
  <div class="span9">
    <div id="etsy-images"></div>
    <div id="etsy-nav" class="row text-center">
      <div class="btn-group">
        <button class="btn etsy-prev">Prev</button>
        <button class="btn etsy-next">Next</button>
      </div>
    </div>
  </div>
</div>

<script>
var page = 1;
$('#item_title').keypress(function(){
  timeout(function(){
    get_page(1);
  }, 1000);
});

var timeout = (function(){
  var timer = 0;
  return function(callback, ms){
    clearTimeout(timer);
    timer = setTimeout(callback, ms);
  }
})();

$(function(){
  $("#etsy-nav").hide();
  $.each({prev: -1, next: 1}, function(key, val){
    $(".etsy-"+key).click(function(){
      page = page + val;
      get_page(page);
    });
  });
});

function get_page(n) {
  var terms = $('#item_title').val();
  var api_key = "crp6v84m4wux42w2b86o78hk";
  var items_per_page = 15;
  if (terms.length > 0) {
    $('#etsy-images').html($('<p>').text('Searching for '+terms));
    $('#etsy-nav').hide();
    $.getJSON("http://openapi.etsy.com/v2/listings/active.js?callback=?", {
      keywords: terms,
      limit: items_per_page,
      offset: Math.max(items_per_page * (n - 1), 0),
      includes: "Images:1",
      api_key: api_key,
    }, function(data) {
      if (data.ok) {
        $('#etsy-nav').show();
        $('#etsy-images').empty();
        if (data.count > 0) {
          $.each(data.results, function(i, item) {
            $("<img>").attr("src", item.Images[0].url_170x135).appendTo("#etsy-images");
          });
        } else {
          $('<p>No results.</p>').appendTo('#etsy-images');
        }
      }

      $("#etsy-images").on("click", "img", function() {
        $("#image").val($(this).attr("src"))
        $("#displayedimage").html($("<img/>").attr("src",$(this).attr("src")))
      });
    });
  }
  return false;
}

$(function(){
  $(".temp-slider").slider({ min: -10, max: 120, range: true, values: [0, 80]});
  $(".precip-slider").slider({ min: 0, max: 100, value: 0});

  $(".temp-value").html($( ".temp-slider" ).slider( "values", 0 ) + '&deg; F - ' + $( ".temp-slider" ).slider( "values", 1 ) + '&deg; F');
  $(".precip-value").html($( ".precip-slider" ).slider( "value" ) + '%');

  $("#item_chance_of_rain").val($( ".precip-slider" ).slider( "value"));
  $("#item_high").val($( ".temp-slider" ).slider( "values", 1 ));
  $("#item_low").val($( ".temp-slider" ).slider( "values", 0 ));

  $(".temp-slider").on( "slidechange", function( event, ui ) {
    $(".temp-value").html($( ".temp-slider" ).slider( "values", 0 ) + '&deg; F - ' + $( ".temp-slider" ).slider( "values", 1 ) + '&deg; F');
    $("#item_high").val($( ".temp-slider" ).slider( "values", 1));
    $("#item_low").val($( ".temp-slider" ).slider( "values", 0 ));
  });

  $(".precip-slider").on( "slidechange", function( event, ui ) {
    $(".precip-value").html($( ".precip-slider" ).slider( "value" ) + '%');
    $("#item_chance_of_rain").val($( ".precip-slider" ).slider( "value"));
  });
});

</script>

FinalProject/FinalProject/app/views/layouts/_navigation.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" id="navigation">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">WTF Should I Wear?</a>
      <div class="nav-collapse collapse">
        <ul class="nav pull-right">
          <div id="user_nav">
            <% if current_user %>
              <%= image_tag current_user.user_image_url, :id=>"user_icon"%>
              <span id="navigation_text">Signed in as <strong color="white"><%= current_user.name %></strong></span>
              <%= link_to "Sign out", signout_path, id: "sign_out", :class => "btn btn-danger" %>
            <% end %>
          </div>
        </ul>
      </div>
    </div>
  </div>
</div>

FinalProject/FinalProject/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WTF Should I Wear?</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navigation' %>
<% if flash[:notice] %> 
  <div class="alert">
    <%= flash[:notice] %>
  </div>
<% end %>
<div class="container">
	<%= yield %>
</div>


</body>
</html>